# Generated by Django 3.2.5 on 2021-08-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Name of the product', max_length=50)),
                ('para', models.TextField(help_text='enter detail of product', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='store_pics')),
            ],
        ),
    ]
