# Generated by Django 3.2.4 on 2021-07-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your full name', max_length=100)),
                ('linkdin_url', models.URLField(help_text='Lindkin profile url')),
                ('Company_name', models.CharField(help_text='Company your are at', max_length=100)),
                ('Company_post', models.CharField(help_text='postion you are at', max_length=100)),
                ('pass_out_year', models.IntegerField(help_text='Your passout year')),
            ],
        ),
    ]
