# Generated by Django 3.2.5 on 2021-07-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alter_socials_pass_out_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socials',
            name='pass_out_year',
            field=models.IntegerField(blank=True, help_text='Your passout year'),
        ),
    ]
