# Generated by Django 3.2.5 on 2021-07-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alter_socials_pass_out_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socials',
            name='pass_out_year',
        ),
    ]
