# Generated by Django 3.2.5 on 2021-07-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_remove_socials_pass_out_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='socials',
            name='photo',
            field=models.ImageField(default='', upload_to='pics'),
            preserve_default=False,
        ),
    ]
